security: update dependencies
tablecheck/tablecheck-react-system pull request #42
Opened 2022-01-11 01:53 UTC by daniellizik

Mainly updating storybook to a version with a more strict version of colors.js

fixes #41

2022-01-11 01:56 UTC, DragonStuff submitted a review, later dismissed

2022-01-11 01:57 UTC, SimeonC requested changes

2022-01-11 01:57 UTC, SimeonC commented on package.json
> +    "@storybook/react": "6.4.10",
You'll need to bump all the storybook versions as they're linked.

2022-01-11 01:57 UTC, gazpachu submitted a review, later dismissed

2022-01-11 01:59 UTC, SimeonC commented
Can you also update the storybook version in the scripts folders as well - we don't want the init script installing bad versions.

2022-01-11 02:00 UTC, daniellizik commented on package.json
> +    "@storybook/react": "6.4.10",
@SimeonC thanks, updated

2022-01-11 02:04 UTC, daniellizik commented
> Can you also update the storybook version in the scripts folders as well - we don't want the init script installing bad versions.

@SimeonC should these be ^6.4.10 or locked to 6.4.10? currently they use fathat. i checked more thoroughly this time and couldn't find any other instance of `@storybook/` besides the root package json and that scripts file you mentioned

2022-01-11 02:40 UTC, SimeonC submitted a review, later dismissed
Thanks! Yea fathat is ok in the init script due to the exact save.

2022-01-11 06:33 UTC, wahidfarid commented on packages/scripts/scripts/init.js
> +  'storybook@^6.4.10'
not sure, can these work if we remove the `^`?

2022-01-11 06:41 UTC, daniellizik commented on packages/scripts/scripts/init.js
> +  'storybook@^6.4.10'
@wahidfarid see this comment https://github.com/tablecheck/tablecheck-react-system/pull/42#issuecomment-1009532335

2022-01-12 10:34 UTC, wahidfarid approved these changes

2022-01-12 10:36 UTC, SimeonC approved these changes

2022-01-13 00:55 UTC, merged

2022-01-14 08:02 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/eslint-config@1.6.0`](https://github.com/tablecheck/tablecheck-react-system/releases/tag/%40tablecheck/eslint-config%401.6.0), [`@tablecheck/scripts@1.10.0`](https://github.com/tablecheck/tablecheck-react-system/releases/tag/%40tablecheck/scripts%401.10.0) :rocket: