fix(scripts): use correct Babel preset-react plugin options
tablecheck/tablecheck-react-system pull request #74
Opened 2022-08-25 10:57 UTC by SashaShostyr

For projects that do not have "@emotion/react" dependency use default
react options for Babel preset-react plugin.

2022-08-26 00:17 UTC, wahidfarid submitted a review, later dismissed

2022-08-26 04:31 UTC, SimeonC requested changes

2022-08-26 04:31 UTC, SimeonC commented on packages/scripts/scripts/utils/package.js
> +    'package.json'
This won't work in a mono repo as the cwd it's the root directory not the directory of the sub package we're building

2022-08-26 04:31 UTC, SimeonC commented on packages/scripts/scripts/rollup/__snapshots__/jsxPlugin.spec.js.snap
> +  }), /*#__PURE__*/React.createElement(components.SomeProp, null, \\"Children\\"), /*#__PURE__*/React.createElement(DefaultComponent, null, /*#__PURE__*/React.createElement(\\"div\\", null, \\"Excess
We should have tests for both emotion and normal react. We need to check both sides of the condition work

2022-08-26 11:04 UTC, SashaShostyr commented on packages/scripts/scripts/rollup/__snapshots__/jsxPlugin.spec.js.snap
> +  }), /*#__PURE__*/React.createElement(components.SomeProp, null, \\"Children\\"), /*#__PURE__*/React.createElement(DefaultComponent, null, /*#__PURE__*/React.createElement(\\"div\\", null, \\"Excess
Updated, please review

2022-08-26 11:04 UTC, SashaShostyr commented on packages/scripts/scripts/utils/package.js
> +    'package.json'
Updated, please review

2022-08-27 11:22 UTC, SimeonC requested changes
Thanks for the changes! Just one more change and we're good to go.

2022-08-27 11:22 UTC, SimeonC commented on packages/scripts/scripts/rollup/jsxPlugin.js
> +                  : undefined
We still want the `runtime: 'automatic'` without emotion. This setting adds the auto import with react - see here https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

2022-08-29 06:40 UTC, SashaShostyr commented on packages/scripts/scripts/rollup/jsxPlugin.js
> +                  : undefined
Thanks! Updated

2022-08-29 06:42 UTC, SimeonC approved these changes

2022-08-29 06:42 UTC, SimeonC commented
Nice work! Thanks! 🎉

2022-08-29 07:32 UTC, wahidfarid approved these changes
looks fine but `packages/scripts/scripts` is a bit weird, never noticed it before :D

2022-08-29 07:42 UTC, merged

2022-08-29 07:44 UTC, tablecheck-public-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@tablecheck/scripts@2.3.6`](https://github.com/tablecheck/tablecheck-react-system/releases/tag/%40tablecheck/scripts%402.3.6) :rocket: